### ISSUE TITLE
0.4.0 plugin fails to load, previous rev is fine.

### ISSUE THREAD

**Issue by ibmaster** [sebmos/homebridge-eufy#20]
ERROR LOADING PLUGIN homebridge-eufy:
[1/29/2022, 9:52:37 AM] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/index.js from /usr/lib/node_modules/homebridge-eufy/lib/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eufy/lib/index.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)

**Comment by sebmos** [comment]
What Node & NPM versions to you have?

**Comment by ibmaster** [comment]
Node.js Version	v14.18.2 
Npm Version	v6.14.15

If they are too old now for this plugin, hopefully the plugin updater would warn :)

**Comment by sebmos** [comment]
I've published a change reverting the ES Module. Out of curiosity though - can you check what your `homebridge-eufy` version is?

**Comment by ibmaster** [comment]
I’m on 0.3.5 release currently without any issues

Ben.

**Comment by sebmos** [comment]
Ah ok - I think from version 0.4.0 it would have worked, but this "ES module" reversal update should fix the issue again. ES module change is deferred to a major version update.

Let me know if it works!

**Comment by ibmaster** [comment]
I still only see the 0.4.0 release label. I updated to it again and got the same ES module error originally reported.
Downgraded down to 0.3.5 again and no issues.

Ben.

**Comment by sebmos** [comment]
Can you check what the version of `node-eufy-api` is? I think that would be in this file, based on the error message you posted: `/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/package.json`

It looks to me like there's a mismatch between node-eufy-api and homebridge-eufy here, which is quite confusing!

**Comment by ibmaster** [comment]
Here is what I see for that  node-eufy-api version in json file when I update to 0.4.0 (and it still fails).

{
  "_from": "node-eufy-api@^0.4.0",
  "_id": ***@***.***",
  "_inBundle": false,
  "_integrity": "sha512-m5Kg5USpK8r+rxEoF1fJtIZpt5Gb/DT+ze1T6b0h4tVc2skicdqxtRd0YB1j+pY6v/dqOzRUuMc1PQ+6BlXwMg==",
  "_location": "/homebridge-eufy/node-eufy-api",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "node-eufy-api@^0.4.0",
    "name": "node-eufy-api",
    "escapedName": "node-eufy-api",
    "rawSpec": "^0.4.0",
    "saveSpec": null,
    "fetchSpec": "^0.4.0"
  },

**Comment by ibmaster** [comment]
Deleted plugin entirely, and installed @ale770/homebridge-eufy v0.3.7
Now working again and it doesn't keep bugging me about the plugin being out of date :)
Closing.
